name: PEDIY-Attendance
on:
  schedule:
    - cron: '36 7 * * *'  # UTC 时间的 7:36，对应北京时间的 15:36
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependency(dependencies)
        run: npm install
        
      - name: Random delay in CheckIn
        env:
          PUSHPLUS: ${{ secrets.PUSHPLUS }}
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          delays=(1 2 3 4)
          delay=$((${delays[RANDOM % ${#delays[@]}]} * 60))
          echo "[*] Waiting for $delay seconds..."
          sleep $delay
          node main.js
          
      - name: Keep alive
        uses: gautamkrishnar/keepalive-workflow@master # keep workflows from being suspended when no commit for a long time
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2 # delete some workflows
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 9
